config/routes.rb
Webman::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  #devise_for :users  devise_for :users, :controllers => {:sessions => "sessions"}
  devise_for :users ,:controllers => { :registrations => "registrations" , :sessions => "sessions" ,:passwords => 'passwords'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :web_articles
  resources :web_folders 
  resources :web_links

  root :to => 'home#index'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

   if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard   
      #can :read, :all
	    can :manage, :all
               # allow access to dashboard
#      if user.role? :superadmin
#        can :manage, :all             # allow superadmins to do anything
#      elsif user.role? :manager
#        can :manage, [User, Product]  # allow managers to do anything to products and users
#      elsif user.role? :sales
#        can :update, Product, :hidden => false  # allow sales to only update visible products
#      end

	  else
		  can :access, :rails_admin
	    can :dashboard 
      can :manage, [WebArticle ,WebFolder,WebLink]
	    can :read, [WebMenuItem]
    end


  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation , :remember_me
end

app/models/web_article.rb
class WebArticle < ActiveRecord::Base
    attr_accessible :name, :summary, :content,:web_menu_item_id
    belongs_to :web_menu_item
    #attr_accessor:web_menu_section_id, :menu_type

end

app/models/web_folder.rb
class WebFolder < ActiveRecord::Base
  # attr_accessible :title, :body
attr_accessible :name, :web_menu_item_id
belongs_to :web_menu_item
#attr_accessor:web_menu_section_id, :menu_type
end

app/models/web_link.rb
class WebLink < ActiveRecord::Base
  # attr_accessible :title, :body
attr_accessible :web_menu_item_id, :name, :url 
belongs_to :web_menu_item
#attr_accessor:web_menu_section_id, :menu_type


before_save :clean_url


  def clean_url
    unless self.url =~ /https?:\/\/.*/
       write_attribute :url, "http://" + self.url.to_s
    else
       write_attribute :url, self.url
    end
  end


end

app/models/web_menu_item.rb
class WebMenuItem < ActiveRecord::Base

    belongs_to :web_menu_section
   # attr_accessor :menu_type 
    attr_accessible :name ,:menu_type, :web_menu_section_id, :web_articles_attributes, :web_links_attributes, :web_folders_attributes 
     
    has_many :web_folders , :dependent => :destroy
    has_many :web_links , :dependent => :destroy
    has_many :web_articles, :dependent => :destroy
     	
    accepts_nested_attributes_for :web_articles
    accepts_nested_attributes_for :web_links
    accepts_nested_attributes_for :web_folders

end

app/models/web_menu_section.rb
class WebMenuSection < ActiveRecord::Base
  # attr_accessible :title, :body
    attr_accessible :name ,:web_menu_items_attributes
   
    has_many :web_menu_items , :dependent => :destroy
    accepts_nested_attributes_for :web_menu_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_web_menus




  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end


  private

  def load_web_menus
	@web_menu_sections = WebMenuSection.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!
  def index
    
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  #before_filter :authenticate_user! #, :only => :token
  layout 'webmanager'

end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  #before_filter :authenticate_user! #, :only => :token
  layout 'webmanager'
 
end 

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'webmanager'
  # GET /resource/sign_in
  def new
    super
  end

  def destroy
   super
  end
end

app/controllers/web_articles_controller.rb
class WebArticlesController < ApplicationController
#  before_filter :authenticate_user!
  def index
    @web_articles = WebArticle.all
  end               

  def new
	@web_article = WebArticle.new
  end 


  def show
  	@web_article = WebArticle.find(params[:id])
	respond_to do |format|
	  format.html {}
    end
  end



end

app/controllers/web_folders_controller.rb
class WebFoldersController < ApplicationController
#  before_filter :authenticate_user!


  def show
  	@web_folder = WebFolder.find(params[:id])
	  respond_to do |format|
	  format.html {}
    end
  end



end

app/controllers/web_links_controller.rb
class WebLinksController < ApplicationController
#  before_filter :authenticate_user!


  def show
  	@web_link = WebLink.find(params[:id])
			respond_to do |format|
			 format.html {}
		  end
  end


end

app/controllers/webmenuitems_controller.rb
class Admin::WebmenuitemsController < ApplicationController
#  before_filter :authenticate_user!
  def home
    @web_menu_items = WebMenuItem.find(:all, :conditions => ["name = ?", web_menu_section_id])
  end

  def index
    @web_menu_items = WebMenuItem.find(:all)
  end

  def new
    @web_menu_item = WebMenuItem.new   
  end 


  def sub_menu
    #render :text => params.inspect and return
    @web_menu_item = WebMenuItem.new(params[:web_menu_item]) 
    @web_menu_item.web_articles.build
    @web_menu_item.web_links.build  
    @web_menu_item.web_folders.build
  end 




  def create
   #render :text => params.inspect and return
    begin
    @web_menu_item = WebMenuItem.new(params[:web_menu_item])
          if @web_menu_item.save
            flash[:notice] = 'Menu was successfully created'
            redirect_to admin_webmenuitems_url
          else
              flash[:error] = 'Unable to create Menu item'
            render :action => 'new'
          end
      rescue Exception => exception
           log_exception(exception)
           flash[:error] = "There is a problem to create new menu item"
           redirect_to client_list_url 
     end
  end





end

app/controllers/webmenusections_controller.rb
class Admin::WebmenusectionsController < ApplicationController
   #before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<style>

  body {
font-family: Arial, Helvetica, sans-serif;
font-size: 0.8em;
color: #535548;
background-color: lightGrey;
text-align: center;
margin: 0;
padding: 0;
}

.float-break {
height: 1%;
} 

.hide {
display: none;
}

div#page {
width: 1000px;
margin: 0 auto 0 auto;
text-align: left;
}

div {
display: block;
}

/* Form Elements */

input.button, button, input.defaultbutton {
font-family: Verdana, Arial, Helvetica, sans-serif;
text-align: center;
vertical-align: middle;
font-size: 0.8em;
color: #343434;
}

/* Header */

div#header {
padding-left: 0em;
padding-right: 0em;
padding-top: 0em;
background-color: white;
padding-bottom: 0em;
height: 232px;
}

div#logo {
float: left;
margin: 1em 0 0 1.5em;
}

div#searchbox {
width: 20em;
margin-top: 1.75em;
margin-right: 1em;
text-align: right;
float: right;
}



ul.deepsmallNav {
	display: none;
}
ul.smallNav li:hover > ul {
		display: block;
}



/* Topmeny */


/* Main Content */
div#main-position {
width: 100%;
float: left;
}

div.content-view-full div.class-frontpage {
background-color: white;
padding: 0 0em 0 0em;
}
</style>
<%= javascript_include_tag 'galleria' %>
</head>
<body>
  <div>
				 <%#= link_to "Signin" , new_user_session_path %>
  </div>
  <div id="page" class="nosidemenu noextrainfo section_id_8 subtree_level_0_node_id_2 subtree_level_1_node_id_181 current_node_id_181">
	<div class="Navigation">
		<div id="NavigationInside">
			<ul>
				<% @web_menu_sections.each_with_index do |web_menu_section| %>
				<li>
					<%= link_to web_menu_section.name ,'#' %>
          <ul class="horizontal">
						 <% web_menu_section.web_menu_items.each do |menu_item|%>
							 <li>
									 <%= link_to menu_item.name, '#' %>
								   <div class="extended">
										<div class="arrow-up"></div>
											<ul class="smallNav">
												 <li>
														<%= link_to 'Links','#'%>
													<ul class="deepsmallNav">
														<% menu_item.web_links.each_with_index do |web_link|%>
															<li>
																<%= link_to  web_link.name , web_link_path(web_link) %>													
															</li>
														<% end 	%>
												  </ul>														
												</li>
												<li>
													<%= link_to 'Folders','#'%>
												  <ul class="deepsmallNav">
														<% menu_item.web_folders.each_with_index do |web_folder|%>
														<li>
															<%= link_to  web_folder.name , web_folder_path(web_folder) %>													
														</li>
												    <% end 	%>
												  </ul>					
												</li>

												 <li>
														<%= link_to 'Articles','#'%>
											      <ul class="deepsmallNav">
														 <% menu_item.web_articles.each_with_index do |web_article|%>
														<li>
															<%= link_to  web_article.name , web_article_path(web_article) %>													
														</li>
													  <% end 	%>
												  </ul>	
												</li>
												
											</ul>
										</div>
							 </li>
						 <% end %>
					</ul>
			  </li>
        <%end%>
			</ul>
		</div>
	</div>
</div>

<div class="container">
<%= yield %>
</div>


</body></html>

app/views/layouts/webmanager.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webman</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
   <%= bootstrap_flash %>
  </div>
   <%= yield %>
</div>
</body>
</html>